server:
  port: 8081

spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: nunikasnikun26504228@yandex.ru
    password:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: postgres